[workspace]
resolver = "2"
members = [
    "confetti-box",
]

[workspace.package]
authors = ["G2"]

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.production]
inherits = "release"
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
